### ISSUE TITLE
Problem to install a non gulp- package.

### ISSUE THREAD

**Issue by zussa** [ktty1220/gulp-packages#1]
I'm trying to import a dependency that does not start with gulp-, import fails, it says that there's no dependency with that name, the dependency that i'm trying import is 'imagemin-pngcrush', is there any way to import it using the gulp-packages?

**Comment by ktty1220** [comment]
At this point, there is no good solution for importing non 'gulp-' packages.
I will consider in the future.
Thanks.

**Comment by zussa** [comment]
Ok thanks! :+1:
