### ISSUE TITLE
gulp install - Error: Cannot find module 'npm' :(

### ISSUE THREAD

**Issue by chrxs** [ktty1220/gulp-packages#6]
Hi

perhaps i'm doing something wrong but I get the following error when I run `gulp install`

```
[12:09:35] Starting 'install'...
[12:09:35] 'install' errored after 2.22 ms
[12:09:35] Error: Cannot find module 'npm'
```

my gulpfile.js looks like:

```
var gulp = require('gulp'),
    pkg = require('gulp-packages')(gulp, [
      'sass',
      'pleeease',
      'taskListing'
    ]);
```

I have npm globally installed, i'm not sure why it can't be found, any help would be greatly appreciated :)

Thanks

**Comment by ktty1220** [comment]
Probably it seems to be caused by setting of NODE_PATH.

Please refer to here.
http://stackoverflow.com/questions/5919629/express-module-not-found-when-installed-with-npm

**Comment by ktty1220** [comment]
Seems this issue can be closed. Please re-open if needed.
